src/Entity/Classe/Classe.php
<?php

namespace App\Entity\Classe;

use App\Entity\Skill\Incantation;
use App\Entity\Specialty\Specialty;
use App\Entity\Spell\Spell;
use App\Repository\Classe\ClasseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClasseRepository::class)]
class Classe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $dv = null;

    #[ORM\Column(length: 255)]
    private ?string $armor = null;

    #[ORM\Column(length: 255)]
    private ?string $weapon = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tool = null;

    #[ORM\Column(length: 255)]
    private ?string $save = null;

    #[ORM\Column(length: 255)]
    private ?string $competence = null;

    #[ORM\Column(length: 255)]
    private ?string $equipment1 = null;

    /**
     * @var Collection<int, ClasseByLevel>
     */
    #[ORM\OneToMany(targetEntity: ClasseByLevel::class, mappedBy: 'classe')]
    private Collection $classeByLevels;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $equipment2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $equipment3 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $equipment4 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $equipment5 = null;

    /**
     * @var Collection<int, Spell>
     */
    #[ORM\ManyToMany(targetEntity: Spell::class, mappedBy: 'classes')]
    private Collection $spells;

    #[ORM\Column(length: 255)]
    private ?string $icon = null;

    #[ORM\OneToOne(mappedBy: 'classe', cascade: ['persist', 'remove'])]
    private ?Specialty $specialty = null;

    #[ORM\OneToOne(mappedBy: 'classe', cascade: ['persist', 'remove'])]
    private ?Incantation $incantation = null;

    #[ORM\Column]
    private ?bool $rage = null;

    #[ORM\Column]
    private ?bool $damage = null;

    #[ORM\Column]
    private ?bool $cantrip = null;

    #[ORM\Column]
    private ?bool $knowing_spells = null;

    #[ORM\Column]
    private ?bool $spell = null;

    #[ORM\Column]
    private ?bool $sorcery_point = null;

    #[ORM\Column]
    private ?bool $martial_art = null;

    #[ORM\Column]
    private ?bool $ki = null;

    #[ORM\Column]
    private ?bool $movement_without_armor = null;

    #[ORM\Column]
    private ?bool $slot_space = null;

    #[ORM\Column]
    private ?bool $slot_level = null;

    #[ORM\Column]
    private ?bool $invocation_know = null;

    #[ORM\Column]
    private ?bool $sneak_attack = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 1020)]
    private ?string $descr = null;

    public function __construct()
    {
        $this->classeByLevels = new ArrayCollection();
        $this->spells = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDv(): ?int
    {
        return $this->dv;
    }

    public function setDv(int $dv): static
    {
        $this->dv = $dv;

        return $this;
    }

    public function getArmor(): ?string
    {
        return $this->armor;
    }

    public function setArmor(string $armor): static
    {
        $this->armor = $armor;

        return $this;
    }

    public function getWeapon(): ?string
    {
        return $this->weapon;
    }

    public function setWeapon(string $weapon): static
    {
        $this->weapon = $weapon;

        return $this;
    }

    public function getTool(): ?string
    {
        return $this->tool;
    }

    public function setTool(?string $tool): static
    {
        $this->tool = $tool;

        return $this;
    }

    public function getSave(): ?string
    {
        return $this->save;
    }

    public function setSave(string $save): static
    {
        $this->save = $save;

        return $this;
    }

    public function getCompetence(): ?string
    {
        return $this->competence;
    }

    public function setCompetence(string $competence): static
    {
        $this->competence = $competence;

        return $this;
    }

    public function getEquipment1(): ?string
    {
        return $this->equipment1;
    }

    public function setEquipment1(string $equipment1): static
    {
        $this->equipment1 = $equipment1;

        return $this;
    }

    /**
     * @return Collection<int, ClasseByLevel>
     */
    public function getClasseByLevels(): Collection
    {
        return $this->classeByLevels;
    }

    public function addClasseByLevel(ClasseByLevel $classeByLevel): static
    {
        if (!$this->classeByLevels->contains($classeByLevel)) {
            $this->classeByLevels->add($classeByLevel);
            $classeByLevel->setClasse($this);
        }

        return $this;
    }

    public function removeClasseByLevel(ClasseByLevel $classeByLevel): static
    {
        if ($this->classeByLevels->removeElement($classeByLevel)) {
            // set the owning side to null (unless already changed)
            if ($classeByLevel->getClasse() === $this) {
                $classeByLevel->setClasse(null);
            }
        }

        return $this;
    }

    public function getEquipment2(): ?string
    {
        return $this->equipment2;
    }

    public function setEquipment2(?string $equipment2): static
    {
        $this->equipment2 = $equipment2;

        return $this;
    }

    public function getEquipment3(): ?string
    {
        return $this->equipment3;
    }

    public function setEquipment3(?string $equipment3): static
    {
        $this->equipment3 = $equipment3;

        return $this;
    }

    public function getEquipment4(): ?string
    {
        return $this->equipment4;
    }

    public function setEquipment4(?string $equipment4): static
    {
        $this->equipment4 = $equipment4;

        return $this;
    }

    public function getEquipment5(): ?string
    {
        return $this->equipment5;
    }

    public function setEquipment5(?string $equipment5): static
    {
        $this->equipment5 = $equipment5;

        return $this;
    }

    /**
     * @return Collection<int, Spell>
     */
    public function getSpells(): Collection
    {
        return $this->spells;
    }

    public function addSpell(Spell $spell): static
    {
        if (!$this->spells->contains($spell)) {
            $this->spells->add($spell);
            $spell->addClass($this);
        }

        return $this;
    }

    public function removeSpell(Spell $spell): static
    {
        if ($this->spells->removeElement($spell)) {
            $spell->removeClass($this);
        }

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(string $icon): static
    {
        $this->icon = $icon;

        return $this;
    }

    public function getSpecialty(): ?Specialty
    {
        return $this->specialty;
    }

    public function setSpecialty(?Specialty $specialty): static
    {
        // unset the owning side of the relation if necessary
        if ($specialty === null && $this->specialty !== null) {
            $this->specialty->setClasse(null);
        }

        // set the owning side of the relation if necessary
        if ($specialty !== null && $specialty->getClasse() !== $this) {
            $specialty->setClasse($this);
        }

        $this->specialty = $specialty;

        return $this;
    }

    public function getIncantation(): ?Incantation
    {
        return $this->incantation;
    }

    public function setIncantation(Incantation $incantation): static
    {
        // set the owning side of the relation if necessary
        if ($incantation->getClasse() !== $this) {
            $incantation->setClasse($this);
        }

        $this->incantation = $incantation;

        return $this;
    }

    public function isRage(): ?bool
    {
        return $this->rage;
    }

    public function setRage(bool $rage): static
    {
        $this->rage = $rage;

        return $this;
    }

    public function isDamage(): ?bool
    {
        return $this->damage;
    }

    public function setDamage(bool $damage): static
    {
        $this->damage = $damage;

        return $this;
    }

    public function isCantrip(): ?bool
    {
        return $this->cantrip;
    }

    public function setCantrip(bool $cantrip): static
    {
        $this->cantrip = $cantrip;

        return $this;
    }

    public function isKnowingSpells(): ?bool
    {
        return $this->knowing_spells;
    }

    public function setKnowingSpells(bool $knowing_spells): static
    {
        $this->knowing_spells = $knowing_spells;

        return $this;
    }

    public function isSpell(): ?bool
    {
        return $this->spell;
    }

    public function setSpell(bool $spell): static
    {
        $this->spell = $spell;

        return $this;
    }

    public function isSorceryPoint(): ?bool
    {
        return $this->sorcery_point;
    }

    public function setSorceryPoint(bool $sorcery_point): static
    {
        $this->sorcery_point = $sorcery_point;

        return $this;
    }

    public function isMartialArt(): ?bool
    {
        return $this->martial_art;
    }

    public function setMartialArt(bool $martial_art): static
    {
        $this->martial_art = $martial_art;

        return $this;
    }

    public function isKi(): ?bool
    {
        return $this->ki;
    }

    public function setKi(bool $ki): static
    {
        $this->ki = $ki;

        return $this;
    }

    public function isMovementWithoutArmor(): ?bool
    {

src/Entity/Skill/Skill.php
<?php

namespace App\Entity\Skill;

use App\Entity\Classe\ClasseByLevel;
use App\Repository\Skill\SkillRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SkillRepository::class)]
class Skill
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 2040, nullable: true)]
    private ?string $descr1 = null;

    /**
     * @var Collection<int, ClasseByLevel>
     */
    #[ORM\ManyToMany(targetEntity: ClasseByLevel::class, inversedBy: 'skills')]
    private Collection $classe;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr2 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr3 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr4 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr5 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr6 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr7 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr8 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr9 = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $descr10 = null;

    #[ORM\Column(nullable: true)]
    private ?int $level = null;

    #[ORM\Column]
    private ?bool $optional = null;

    #[ORM\Column]
    private ?bool $show_descr = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $part = null;

    #[ORM\OneToOne(mappedBy: 'skill', cascade: ['persist', 'remove'])]
    private ?SubSkill $subSkill = null;

    #[ORM\OneToOne(mappedBy: 'skill', cascade: ['persist', 'remove'])]
    private ?SkillTable $skillTable = null;

    public function __construct()
    {
        $this->classe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescr1(): ?string
    {
        return $this->descr1;
    }

    public function setDescr1(?string $descr1): static
    {
        $this->descr1 = $descr1;

        return $this;
    }

    /**
     * @return Collection<int, ClasseByLevel>
     */
    public function getClasse(): Collection
    {
        return $this->classe;
    }

    public function addClasse(ClasseByLevel $classe): static
    {
        if (!$this->classe->contains($classe)) {
            $this->classe->add($classe);
        }

        return $this;
    }

    public function removeClasse(ClasseByLevel $classe): static
    {
        $this->classe->removeElement($classe);

        return $this;
    }

    public function getDescr2(): ?string
    {
        return $this->descr2;
    }

    public function setDescr2(?string $descr2): static
    {
        $this->descr2 = $descr2;

        return $this;
    }

    public function getDescr3(): ?string
    {
        return $this->descr3;
    }

    public function setDescr3(?string $descr3): static
    {
        $this->descr3 = $descr3;

        return $this;
    }

    public function getDescr4(): ?string
    {
        return $this->descr4;
    }

    public function setDescr4(?string $descr4): static
    {
        $this->descr4 = $descr4;

        return $this;
    }

    public function getDescr5(): ?string
    {
        return $this->descr5;
    }

    public function setDescr5(?string $descr5): static
    {
        $this->descr5 = $descr5;

        return $this;
    }

    public function getDescr6(): ?string
    {
        return $this->descr6;
    }

    public function setDescr6(?string $descr6): static
    {
        $this->descr6 = $descr6;

        return $this;
    }

    public function getDescr7(): ?string
    {
        return $this->descr7;
    }

    public function setDescr7(?string $descr7): static
    {
        $this->descr7 = $descr7;

        return $this;
    }

    public function getDescr8(): ?string
    {
        return $this->descr8;
    }

    public function setDescr8(?string $descr8): static
    {
        $this->descr8 = $descr8;

        return $this;
    }

    public function getDescr9(): ?string
    {
        return $this->descr9;
    }

    public function setDescr9(?string $descr9): static
    {
        $this->descr9 = $descr9;

        return $this;
    }

    public function getDescr10(): ?string
    {
        return $this->descr10;
    }

    public function setDescr10(?string $descr10): static
    {
        $this->descr10 = $descr10;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(?int $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function isOptional(): ?bool
    {
        return $this->optional;
    }

    public function setOptional(bool $optional): static
    {
        $this->optional = $optional;

        return $this;
    }

    public function isShowDescr(): ?bool
    {
        return $this->show_descr;
    }

    public function setShowDescr(bool $show_descr): static
    {
        $this->show_descr = $show_descr;

        return $this;
    }

    public function getPart(): ?string
    {
        return $this->part;
    }

    public function setPart(?string $part): static
    {
        $this->part = $part;

        return $this;
    }

    public function getSubSkill(): ?SubSkill
    {
        return $this->subSkill;
    }

    public function setSubSkill(SubSkill $subSkill): static
    {
        // set the owning side of the relation if necessary
        if ($subSkill->getSkill() !== $this) {
            $subSkill->setSkill($this);
        }

        $this->subSkill = $subSkill;

        return $this;
    }

    public function getSkillTable(): ?SkillTable
    {
        return $this->skillTable;
    }

    public function setSkillTable(?SkillTable $skillTable): static
    {
        // unset the owning side of the relation if necessary
        if ($skillTable === null && $this->skillTable !== null) {
            $this->skillTable->setSkill(null);
        }

        // set the owning side of the relation if necessary
        if ($skillTable !== null && $skillTable->getSkill() !== $this) {
            $skillTable->setSkill($this);
        }

        $this->skillTable = $skillTable;

        return $this;
    }
}

templates/client/classe/construct/_skills-table.html.twig
<table class="classe-skill-table">
    <thead class="classe-skill-thead">
        <tr class="classe-skill-tr">
            <th class="classe-skill-th">{{ skill.skillTable.th1 }}</th>
            <th class="classe-skill-th">{{ skill.skillTable.th2 }}</th>
            {% if skill.skillTable.th3 %}
                <th class="classe-skill-th">{{ skill.skillTable.th3 }}</th>
            {% endif %}
            {% if skill.skillTable.th4 %}
                <th class="classe-skill-th">{{ skill.skillTable.th4 }}</th>
            {% endif %}
        </tr>
    </thead>
    <tbody class="classe-skill-tbody">
        <tr class="classe-skill-tr">
            <td class="classe-skill-td">{{ skill.skillTable.tr1Td1 }}</td>
            <td class="classe-skill-td">{{ skill.skillTable.tr1Td2 }}</td>
            {% if skill.skillTable.tr1Td3 %}
                <td class="classe-skill-td">{{ skill.skillTable.tr1Td3 }}</td>
            {% endif %}
            {% if skill.skillTable.tr1Td4 %}
                <td class="classe-skill-td">{{ skill.skillTable.tr1Td4 }}</td>
            {% endif %}
        </tr>
        {% if skill.skillTable.tr2Td1 %}
            <tr class="classe-skill-tr">
                <td class="classe-skill-td">{{ skill.skillTable.tr2Td1 }}</td>
                <td class="classe-skill-td">{{ skill.skillTable.tr2Td2 }}</td>
                {% if skill.skillTable.tr2Td3 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr2Td3 }}</td>
                {% endif %}
                {% if skill.skillTable.tr2Td4 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr2Td4 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if skill.skillTable.tr3Td1 %}
            <tr class="classe-skill-tr">
                <td class="classe-skill-td">{{ skill.skillTable.tr3Td1 }}</td>
                <td class="classe-skill-td">{{ skill.skillTable.tr3Td2 }}</td>
                {% if skill.skillTable.tr3Td3 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr3Td3 }}</td>
                {% endif %}
                {% if skill.skillTable.tr3Td4 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr3Td4 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if skill.skillTable.tr4Td1 %}
            <tr class="classe-skill-tr">
                <td class="classe-skill-td">{{ skill.skillTable.tr4Td1 }}</td>
                <td class="classe-skill-td">{{ skill.skillTable.tr4Td2 }}</td>
                {% if skill.skillTable.tr4Td3 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr4Td3 }}</td>
                {% endif %}
                {% if skill.skillTable.tr4Td4 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr4Td4 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if skill.skillTable.tr5Td1 %}
            <tr class="classe-skill-tr">
                <td class="classe-skill-td">{{ skill.skillTable.tr5Td1 }}</td>
                <td class="classe-skill-td">{{ skill.skillTable.tr5Td2 }}</td>
                {% if skill.skillTable.tr5Td3 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr5Td3 }}</td>
                {% endif %}
                {% if skill.skillTable.tr5Td4 %}
                    <td class="classe-skill-td">{{ skill.skillTable.tr5Td4 }}</td>
                {% endif %}
            </tr>
        {% endif %}
    </tbody>
</table>

templates/client/classe/construct/_skills.html.twig
{% set newArray = [] %}
{% for level in classe.classeByLevels %}
    {% for skill in level.skills|sort((a, b) => a.level <=> b.level) %}
        {% if skill.showDescr == true %}
            {% if skill.name not in newArray %}
                <div class="classe-skill-div">
                    <h3 class="classe-skill-title">
                        {{ skill.name }} 
                        {% if skill.optional == true %}
                            (Facultatif)
                        {% endif %}
                    </h3>
                    {% if skill.descr1 %}
                        <p class="classe-skill-descr">{{ skill.descr1|raw }}</p>
                    {% endif %}
                    {% if skill.descr2 %}
                        <p class="classe-skill-descr">{{ skill.descr2|raw }}<p>
                    {% endif %}
                    {% if skill.descr3 %}
                        <p class="classe-skill-descr">{{ skill.descr3|raw }}<p>
                    {% endif %}
                    {% if skill.descr4 %}
                        <p class="classe-skill-descr">{{ skill.descr4|raw }}<p>
                    {% endif %}
                    {% if skill.descr5 %}
                        <p class="classe-skill-descr">{{ skill.descr5|raw }}<p>
                    {% endif %}
                    {% if skill.descr6 %}
                        <p class="classe-skill-descr">{{ skill.descr6|raw }}<p>
                    {% endif %}
                    {% if skill.descr7 %}
                        <p class="classe-skill-descr">{{ skill.descr7|raw }}<p>
                    {% endif %}
                    {% if skill.descr8 %}
                        <p class="classe-skill-descr">{{ skill.descr8|raw }}<p>
                    {% endif %}
                    {% if skill.descr9 %}
                        <p class="classe-skill-descr">{{ skill.descr9|raw }}<p>
                    {% endif %}
                    {% if skill.descr10 %}
                        <p class="classe-skill-descr">{{ skill.descr10|raw }}<p>
                    {% endif %}

                    {# spelling #}
                    {% include 'client/classe/construct/_spelling.html.twig' %}
    
                    {% if skill.subSkill %}
                        <h4 class="classe-skill-subtitle">{{ skill.subSkill.title1 }}</h4>
                        <p class="classe-skill-descr">{{ skill.subSkill.descrOne }}</p>
                        {% if skill.subSkill.descrOne2 %}
                            <p class="classe-skill-descr">{{ skill.subSkill.descrOne2 }}</p>
                        {% endif %}
                    {% endif %}

                    {% if skill.skillTable %}
                        {% include 'client/classe/construct/_skills-table.html.twig' %}
                    {% endif %}

                </div>
                {% set newArray = newArray|merge([skill.name]) %}
            {% endif %}
        {% endif %}
    {% endfor %}
{% endfor %}

templates/client/classe/construct/_specialties.html.twig
<div class="classe-specialty">
    <h5 class="classe-specialty-title">{{ classe.specialty.name }}</h5>
    <p class="classe-specialty-descr">{{ classe.specialty.descr1|raw }}</p>
    <table class="classe-specialty-table">
        <thead class="classe-specialty-thead">
            <tr class="classe-specialty-tr">
                <th class="classe-specialty-th">{{ classe.specialty.name }}</th>
                <th class="classe-specialty-th">Source</th>
            </tr>
        </thead>
        <tbody class="classe-specialty-tbody">
            {% for specialty in classe.specialty.specialtyItems|sort((a, b) => a.slug <=> b.slug) %}
                {% if specialty.ua == false %}
                    <tr class="classe-specialty-tr">
                        <td class="classe-specialty-td">
                            <a class="classe-specialty-link" href="{{ path('app_view_specialty_show', { 'slug': classe.slug, 'slug2': specialty.slug }) }}">{{ specialty.name }}</a>
                        </td>
                        <td class="classe-specialty-td">{{ specialty.source }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            <tr class="classe-specialty-tr">
                <th class="classe-specialty-th" colspan="2">Archives des Arcanes Déterrées</th>
            </tr>
            {% for specialty in classe.specialty.specialtyItems|sort((a, b) => a.slug <=> b.slug) %}
                {% if specialty.ua == true %}
                    <tr class="classe-specialty-tr">
                        <td class="classe-specialty-td">
                            <a class="classe-specialty-link" href="{{ path('app_view_specialty_show', { 'slug': classe.slug, 'slug2': specialty.slug }) }}">{{ specialty.name }}</a>
                        </td>
                        <td class="classe-specialty-td">{{ specialty.source }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

templates/client/classe/construct/_tables.html.twig
<table class="classe-table">
    <thead class="classe-thead">
        <tr class="classe-thead-tr">
            <th class="classe-th" {% if classe.spell == true %}rowspan="2"{% endif %}>Niv</th>
            <th class="classe-th" {% if classe.spell == true %}rowspan="2"{% endif %}>BM</th>
            
            {% if classe.sorceryPoint == true %}
                <th class="classe-th" rowspan="2">Points de sorcellerie</th>
            {% endif %}

            <th class="classe-th" {% if classe.spell == true %}rowspan="2"{% endif %}>Capacités</th>
            
            {% if classe.rage == true %}
                <th class="classe-th">Rages</th>
            {% endif %}
            {% if classe.damage == true %}
                <th class="classe-th">Dégâts</th>
            {% endif %}
            {% if classe.cantrip == true %}
                <th class="classe-th" {% if classe.spell == true %}rowspan="2"{% endif %}>Cantrips connus</th>
            {% endif %}
            {% if classe.knowingSpells == true %}
                <th class="classe-th" {% if classe.spell == true %}rowspan="2"{% endif %}>Sorts connus</th>
            {% endif %}
            {% if classe.spell == true %}
                <th class="classe-th colspan" colspan="9">-Emplacements de sorts-</th>
            {% endif %}

        </tr>
        {% if classe.spell == true %}
            <tr class="classe-thead-tr">
                <th class="classe-th">1</th> 
                <th class="classe-th">2</th> 
                <th class="classe-th">3</th> 
                <th class="classe-th">4</th> 
                <th class="classe-th">5</th> 
                <th class="classe-th">6</th> 
                <th class="classe-th">7</th> 
                <th class="classe-th">8</th> 
                <th class="classe-th">9</th> 
            </tr>
        {% endif %}
    </thead>
    <tbody class="classe-tbody">
        {% for level in classe.classeByLevels %}
            <tr class="classe-tbody-tr">
                <td class="classe-td">{{ level.level }}</td>
                <td class="classe-td">+{{ level.bm }}</td>

                {% if classe.sorceryPoint == true %}
                    {% if level.sorceryPoint %}
                        <td class="classe-td">{{ level.sorceryPoint }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {% endif %}
                {% endif %}

                <td class="classe-td skills">
                    {% for skill in level.skills %}
                        {% if skill.optional == false %}
                            {{ skill.name }} 
                            {% if skill.part %}
                                {{ skill.part }}
                            {% endif %}
                        {% elseif skill.optional == true %}
                            <i>{{ skill.name }} (Facultatif)</i> 
                            {% if skill.part %}
                                {{ skill.part }}
                            {% endif %}
                        {% endif %}
                        {{ not loop.last ? ',' }}
                    {% endfor %}
                </td>

                {% if classe.rage == true %}
                    <td class="classe-td">{{ level.rage }}</td>
                {% endif %}
                {% if classe.damage == true %}
                    <td class="classe-td">+{{ level.damage }}</td>
                {% endif %}
                {% if classe.cantrip == true %}
                    <td class="classe-td">{{ level.cantrip }}</td>
                {% endif %}
                {% if classe.knowingSpells == true %}
                    <td class="classe-td">{{ level.knowingSpells }}</td>
                {% endif %}
                {% if classe.spell == true %}
                    <td class="classe-td">{{ level.spellOne }}</td>
                    {% if level.spellTwo %}
                        <td class="classe-td">{{ level.spellTwo }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                    {% if level.spellThree %}
                        <td class="classe-td">{{ level.spellThree }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                    {% if level.spellFour %}
                        <td class="classe-td">{{ level.spellFour }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                    {% if level.spellFive %}
                        <td class="classe-td">{{ level.spellFive }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                    {% if level.spellSix %}
                        <td class="classe-td">{{ level.spellSix }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                    {% if level.spellSeven %}
                        <td class="classe-td">{{ level.spellSeven }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                    {% if level.spellEight %}
                        <td class="classe-td">{{ level.spellEight }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                    {% if level.spellNine %}
                        <td class="classe-td">{{ level.spellNine }}</td>
                    {% else %}
                        <td class="classe-td">-</td>
                    {%  endif %}
                {% endif %}

            </tr>
        {% endfor %}
    </tbody>
</table>