src/Entity/Race/SourceRace.php
<?php

namespace App\Entity\Race;

use App\Entity\Source\Part;
use App\Entity\Source\Source;
use App\Entity\Talent\Talent;
use App\Repository\Race\SourceRaceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SourceRaceRepository::class)]
class SourceRace
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'sourceRaces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Race $race = null;
    
    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $descr1 = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $descr2 = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $descr3 = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $descr4 = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $descr5 = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $ability_inc = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $age = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $alignment = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $size = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $speed = null;

    #[ORM\Column(length: 1050, nullable: true)]
    private ?string $language = null;

    /**
     * @var Collection<int, Subrace>
     */
    #[ORM\OneToMany(targetEntity: Subrace::class, mappedBy: 'source')]
    private Collection $subraces;

    /**
     * @var Collection<int, Talent>
     */
    #[ORM\ManyToMany(targetEntity: Talent::class, mappedBy: 'race')]
    private Collection $talent;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'races')]
    private ?Source $source = null;

    #[ORM\ManyToOne(inversedBy: 'races')]
    private ?Part $sourcePart = null;

    public function __construct()
    {
        $this->subraces = new ArrayCollection();
        $this->talent = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRace(): ?Race
    {
        return $this->race;
    }

    public function setRace(?Race $race): static
    {
        $this->race = $race;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescr1(): ?string
    {
        return $this->descr1;
    }

    public function setDescr1(?string $descr1): static
    {
        $this->descr1 = $descr1;

        return $this;
    }

    public function getDescr2(): ?string
    {
        return $this->descr2;
    }

    public function setDescr2(?string $descr2): static
    {
        $this->descr2 = $descr2;

        return $this;
    }

    public function getDescr3(): ?string
    {
        return $this->descr3;
    }

    public function setDescr3(?string $descr3): static
    {
        $this->descr3 = $descr3;

        return $this;
    }

    public function getDescr4(): ?string
    {
        return $this->descr4;
    }

    public function setDescr4(?string $descr4): static
    {
        $this->descr4 = $descr4;

        return $this;
    }

    public function getDescr5(): ?string
    {
        return $this->descr5;
    }

    public function setDescr5(?string $descr5): static
    {
        $this->descr5 = $descr5;

        return $this;
    }

    public function getAbilityInc(): ?string
    {
        return $this->ability_inc;
    }

    public function setAbilityInc(?string $ability_inc): static
    {
        $this->ability_inc = $ability_inc;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->age;
    }

    public function setAge(?string $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function getAlignment(): ?string
    {
        return $this->alignment;
    }

    public function setAlignment(?string $alignment): static
    {
        $this->alignment = $alignment;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(?string $size): static
    {
        $this->size = $size;

        return $this;
    }

    public function getSpeed(): ?string
    {
        return $this->speed;
    }

    public function setSpeed(?string $speed): static
    {
        $this->speed = $speed;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(?string $language): static
    {
        $this->language = $language;

        return $this;
    }

    /**
     * @return Collection<int, Subrace>
     */
    public function getSubraces(): Collection
    {
        return $this->subraces;
    }

    public function addSubrace(Subrace $subrace): static
    {
        if (!$this->subraces->contains($subrace)) {
            $this->subraces->add($subrace);
            $subrace->setSource($this);
        }

        return $this;
    }

    public function removeSubrace(Subrace $subrace): static
    {
        if ($this->subraces->removeElement($subrace)) {
            // set the owning side to null (unless already changed)
            if ($subrace->getSource() === $this) {
                $subrace->setSource(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Talent>
     */
    public function getTalent(): Collection
    {
        return $this->talent;
    }

    public function addTalent(Talent $talent): static
    {
        if (!$this->talent->contains($talent)) {
            $this->talent->add($talent);
            $talent->addRace($this);
        }

        return $this;
    }

    public function removeTalent(Talent $talent): static
    {
        if ($this->talent->removeElement($talent)) {
            $talent->removeRace($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSource(): ?Source
    {
        return $this->source;
    }

    public function setSource(?Source $source): static
    {
        $this->source = $source;

        return $this;
    }

    public function getSourcePart(): ?Part
    {
        return $this->sourcePart;
    }

    public function setSourcePart(?Part $sourcePart): static
    {
        $this->sourcePart = $sourcePart;

        return $this;
    }
}

src/Form/Race/RaceType.php
<?php

namespace App\Form\Race;

use App\Entity\Race\Race;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('slug', TextType::class)
            ->add('type', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Race::class,
        ]);
    }
}

src/Controller/BO/Race/RaceController.php
<?php

namespace App\Controller\BO\Race;

use App\Entity\Race\Race;
use App\Form\Race\RaceType;
use App\Repository\Race\RaceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/race')]
final class RaceController extends AbstractController
{
    #[Route(name: 'app_race_index', methods: ['GET'])]
    public function index(RaceRepository $raceRepository): Response
    {
        return $this->render('bo/races/race/index.html.twig', [
            'races' => $raceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_race_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $race = new Race();
        $form = $this->createForm(RaceType::class, $race);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($race);
            $entityManager->flush();

            return $this->redirectToRoute('app_race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('bo/races/race/new.html.twig', [
            'race' => $race,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_race_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Race $race, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RaceType::class, $race);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('bo/races/race/edit.html.twig', [
            'race' => $race,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_race_delete', methods: ['POST'])]
    public function delete(Request $request, Race $race, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$race->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($race);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_race_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/BO/Race/SourceRaceController.php
<?php

namespace App\Controller\BO\Race;

use App\Entity\Race\SourceRace;
use App\Form\Race\SourceRaceType;
use App\Repository\Race\SourceRaceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/race-source')]
final class SourceRaceController extends AbstractController
{
    #[Route(name: 'app_source_race_index', methods: ['GET'])]
    public function index(SourceRaceRepository $sourceRaceRepository): Response
    {
        return $this->render('bo/races/source_race/index.html.twig', [
            'source_races' => $sourceRaceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_source_race_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $sourceRace = new SourceRace();
        $form = $this->createForm(SourceRaceType::class, $sourceRace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($sourceRace);
            $entityManager->flush();

            return $this->redirectToRoute('app_source_race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('bo/races/source_race/new.html.twig', [
            'source_race' => $sourceRace,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_source_race_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, SourceRace $sourceRace, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SourceRaceType::class, $sourceRace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_source_race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('bo/races/source_race/edit.html.twig', [
            'source_race' => $sourceRace,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_source_race_delete', methods: ['POST'])]
    public function delete(Request $request, SourceRace $sourceRace, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sourceRace->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($sourceRace);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_source_race_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/BO/Race/SubraceController.php
<?php

namespace App\Controller\BO\Race;

use App\Entity\Race\Subrace;
use App\Form\Race\SubraceType;
use App\Repository\Race\SubraceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/subrace')]
final class SubraceController extends AbstractController
{
    #[Route(name: 'app_subrace_index', methods: ['GET'])]
    public function index(SubraceRepository $subraceRepository): Response
    {
        return $this->render('bo/races/subrace/index.html.twig', [
            'subraces' => $subraceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_subrace_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $subrace = new Subrace();
        $form = $this->createForm(SubraceType::class, $subrace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($subrace);
            $entityManager->flush();

            return $this->redirectToRoute('app_subrace_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('bo/races/subrace/new.html.twig', [
            'subrace' => $subrace,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_subrace_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Subrace $subrace, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SubraceType::class, $subrace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_subrace_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('bo/races/subrace/edit.html.twig', [
            'subrace' => $subrace,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_subrace_delete', methods: ['POST'])]
    public function delete(Request $request, Subrace $subrace, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$subrace->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($subrace);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_subrace_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/client/race/construct/_source-talent.html.twig
{# sourceRace talents #}
{% for talent in source.talent %}
    <h4 class="race-talent-title">{{ talent.name }}</h4>
    <p class="race-talent-description">{{ talent.descr1|raw }}</p>

    {# talent description #}
    {% if talent.descr2 %}
        <p class="race-talent-description">{{ talent.descr2|raw }}</p>
    {% endif %}
    {% if talent.descr3 %}
        <p class="race-talent-description">{{ talent.descr3|raw }}</p>
    {% endif %}
    {% if talent.descr4 %}
        <p class="race-talent-description">{{ talent.descr4|raw }}</p>
    {% endif %}
    {% if talent.descr5 %}
        <p class="race-talent-description">{{ talent.descr5|raw }}</p>
    {% endif %}
    {% if talent.descr6 %}
        <p class="race-talent-description">{{ talent.descr6|raw }}</p>
    {% endif %}
    {% if talent.descr7 %}
        <p class="race-talent-description">{{ talent.descr7|raw }}</p>
    {% endif %}
    {% if talent.descr8 %}
        <p class="race-talent-description">{{ talent.descr8|raw }}</p>
    {% endif %}
    {% if talent.descr9 %}
        <p class="race-talent-description">{{ talent.descr9|raw }}</p>
    {% endif %}
    {% if talent.descr10 %}
        <p class="race-talent-description">{{ talent.descr10|raw }}</p>
    {% endif %}

    {% if talent.talentTable %}
        {% include 'client/race/construct/_talent-table.html.twig' %}
    {% endif %}

{% endfor %}

templates/client/race/construct/_source.html.twig
{# sourceRace #}
{% for source in race.sourceRaces %}
    <h2 class="race-source-title" id="{{ source.slug }}">{{ source.name }}</h2>

    {# sourceRace items #}
    {% if source.descr1 %}
        <p class="race-description">{{ source.descr1|raw }}
    {% endif %}
    {% if source.descr2 %}
        <p class="race-description">{{ source.descr2|raw }}
    {% endif %}
    {% if source.descr3 %}
        <p class="race-description">{{ source.descr3|raw }}
    {% endif %}
    {% if source.descr4 %}
        <p class="race-description">{{ source.descr4|raw }}
    {% endif %}
    {% if source.descr5 %}
        <p class="race-description">{{ source.descr5|raw }}
    {% endif %}
    {% if source.abilityInc %}
        <p class="race-item"><b>Amélioration de score de capacité : </b>{{ source.abilityInc }}</p>
    {% endif %}
    {% if source.type %}
        <p class="race-item"><b>Type : </b>{{ source.type }}</p>
    {% endif %}
    {% if source.age %}
        <p class="race-item"><b>Âge : </b>{{ source.age }}</p>
    {% endif %}
    {% if source.alignment %}
        <p class="race-item"><b>Alignement : </b>{{ source.alignment }}</p>
    {% endif %}
    {% if source.size %}
        <p class="race-item"><b>Taille : </b>{{ source.size }}</p>
    {% endif %}
    {% if source.speed %}
        <p class="race-item"><b>Vitesse : </b>{{ source.speed }}</p>
    {% endif %}
    {% if source.language %}
        <p class="race-item"><b>Languages : </b>{{ source.language }}</p>
    {% endif %}

    {% include 'client/race/construct/_source-talent.html.twig' %}

    {% include 'client/race/construct/_subrace.html.twig' %}

{% endfor %}

templates/client/race/construct/_subrace-talent.html.twig
{# subrace talents #}
{% for talent in subrace.talent %}
    <h4 class="race-talent-title">{{ talent.name }}</h4>
    <p class="race-talent-description">{{ talent.descr1|raw }}</p>

    {# talent description #}
    {% if talent.descr2 %}
        <p class="race-talent-description">{{ talent.descr2|raw }}</p>
    {% endif %}
    {% if talent.descr3 %}
        <p class="race-talent-description">{{ talent.descr3|raw }}</p>
    {% endif %}
    {% if talent.descr4 %}
        <p class="race-talent-description">{{ talent.descr4|raw }}</p>
    {% endif %}
    {% if talent.descr5 %}
        <p class="race-talent-description">{{ talent.descr5|raw }}</p>
    {% endif %}
    {% if talent.descr6 %}
        <p class="race-talent-description">{{ talent.descr6|raw }}</p>
    {% endif %}
    {% if talent.descr7 %}
        <p class="race-talent-description">{{ talent.descr7|raw }}</p>
    {% endif %}
    {% if talent.descr8 %}
        <p class="race-talent-description">{{ talent.descr8|raw }}</p>
    {% endif %}
    {% if talent.descr9 %}
        <p class="race-talent-description">{{ talent.descr9|raw }}</p>
    {% endif %}
    {% if talent.descr10 %}
        <p class="race-talent-description">{{ talent.descr10|raw }}</p>
    {% endif %}

    {% if talent.talentTable %}
        {% include 'client/race/construct/_talent-table.html.twig' %}
    {% endif %}

{% endfor %}

templates/client/race/construct/_subrace.html.twig
{# subrace #}
<div class="race-subrace">
    {% for subrace in source.subraces %}
        <h3 class="race-subrace-title" id="{{ source.slug }}-{{ subrace.slug }}">{{ subrace.name }}</h3>

        {# subrace items #}
        {% if subrace.book %}
            <p class="race-book">Source : {{ subrace.book }}</p>
        {% endif %}
        {% if subrace.descr1 %}
            <p class="race-description">{{ subrace.descr1|raw }}
        {% endif %}
        {% if subrace.descr2 %}
            <p class="race-description">{{ subrace.descr2|raw }}
        {% endif %}
        {% if subrace.descr3 %}
            <p class="race-description">{{ subrace.descr3|raw }}
        {% endif %}
        {% if subrace.descr4 %}
            <p class="race-description">{{ subrace.descr4|raw }}
        {% endif %}
        {% if subrace.descr5 %}
            <p class="race-description">{{ subrace.descr5|raw }}
        {% endif %}
        {% if subrace.abilityInc %}
            <p class="race-item"><b>Amélioration de score de capacité : </b>{{ subrace.abilityInc }}</p>
        {% endif %}
        {% if subrace.type %}
            <p class="race-item"><b>Type : </b>{{ subrace.type }}</p>
        {% endif %}
        {% if subrace.age %}
            <p class="race-item"><b>Âge : </b>{{ subrace.age }}</p>
        {% endif %}
        {% if subrace.alignment %}
            <p class="race-item"><b>Alignement : </b>{{ subrace.alignment }}</p>
        {% endif %}
        {% if subrace.size %}
            <p class="race-item"><b>Taille : </b>{{ subrace.size }}</p>
        {% endif %}
        {% if subrace.speed %}
            <p class="race-item"><b>Vitesse : </b>{{ subrace.speed }}</p>
        {% endif %}
        {% if subrace.language %}
            <p class="race-item"><b>Languages : </b>{{ subrace.language }}</p>
        {% endif %}
        
        {% include 'client/race/construct/_subrace-talent.html.twig' %}

    {% endfor %}
</div>

templates/client/race/construct/_talent-table.html.twig
<table class="talent-table">
    <thead>
        {% if talent.talentTable.name %}
            <tr>
                <th colspan="2">{{ talent.talentTable.name }}</th>
            </tr>
        {% endif %}
        <tr>
            <th>{{ talent.talentTable.th1 }}</th>
            <th>{{ talent.talentTable.th2 }}</th>
            {% if talent.talentTable.th3 %}
                <th>{{ talent.talentTable.th3 }}</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ talent.talentTable.tr1Td1 }}</td>
            <td>{{ talent.talentTable.tr1Td2 }}</td>
            {% if talent.talentTable.tr1Td3 %}
                <td>{{ talent.talentTable.tr1Td3 }}</td>
            {% endif %}
        </tr>
        {% if talent.talentTable.tr2td1 %}
            <tr>
                <td>{{ talent.talentTable.tr2Td1 }}</td>
                <td>{{ talent.talentTable.tr2Td2 }}</td>
                {% if talent.talentTable.tr2Td3 %}
                    <td>{{ talent.talentTable.tr2Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr3td1 %}
            <tr>
                <td>{{ talent.talentTable.tr3Td1 }}</td>
                <td>{{ talent.talentTable.tr3Td2 }}</td>
                {% if talent.talentTable.tr3Td3 %}
                    <td>{{ talent.talentTable.tr3Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr4td1 %}
            <tr>
                <td>{{ talent.talentTable.tr4Td1 }}</td>
                <td>{{ talent.talentTable.tr4Td2 }}</td>
                {% if talent.talentTable.tr4Td3 %}
                    <td>{{ talent.talentTable.tr4Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr5td1 %}
            <tr>
                <td>{{ talent.talentTable.tr5Td1 }}</td>
                <td>{{ talent.talentTable.tr5Td2 }}</td>
                {% if talent.talentTable.tr5Td3 %}
                    <td>{{ talent.talentTable.tr5Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr6td1 %}
            <tr>
                <td>{{ talent.talentTable.tr6Td1 }}</td>
                <td>{{ talent.talentTable.tr6Td2 }}</td>
                {% if talent.talentTable.tr6Td3 %}
                    <td>{{ talent.talentTable.tr6Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr7td1 %}
            <tr>
                <td>{{ talent.talentTable.tr7Td1 }}</td>
                <td>{{ talent.talentTable.tr7Td2 }}</td>
                {% if talent.talentTable.tr7Td3 %}
                    <td>{{ talent.talentTable.tr7Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr8td1 %}
            <tr>
                <td>{{ talent.talentTable.tr8Td1 }}</td>
                <td>{{ talent.talentTable.tr8Td2 }}</td>
                {% if talent.talentTable.tr8Td3 %}
                    <td>{{ talent.talentTable.tr8Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr9td1 %}
            <tr>
                <td>{{ talent.talentTable.tr9Td1 }}</td>
                <td>{{ talent.talentTable.tr9Td2 }}</td>
                {% if talent.talentTable.tr9Td3 %}
                    <td>{{ talent.talentTable.tr9Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
        {% if talent.talentTable.tr10td1 %}
            <tr>
                <td>{{ talent.talentTable.tr10Td1 }}</td>
                <td>{{ talent.talentTable.tr10Td2 }}</td>
                {% if talent.talentTable.tr10Td3 %}
                    <td>{{ talent.talentTable.tr10Td3 }}</td>
                {% endif %}
            </tr>
        {% endif %}
    </tbody>
</table>
        